//FOR LOGIN
export const GET_ALL_FAVOURITES  = 'GET_ALL_FAVOURITES';
export const ADD_FAVOURITE  = 'ADD_FAVOURITE';
export const DELETE_FAVOURITE  = 'DELETE_FAVOURITE';
export const FAVOURITES_FAILED   = 'FAVOURITES_FAILED';
export const ATTEMPTING_FAVOURITES  = 'ATTEMPTING_FAVOURITES';