//FOR LOGIN
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS';
export const LOGIN_FAILED   = 'LOGIN_FAILED';
export const ATTEMPTING_LOGIN  = 'ATTEMPTING_LOGIN';

//FOR LOGOUT
export const LOGOUT = 'LOGOUT';

//FOR SLIDER
export const SLIDER_INIT   = 'SLIDER_INIT';
export const SLIDER_FAILED  = 'SLIDER_FAILED';
export const ATTEMPTING_SLIDER  = 'ATTEMPTING_SLIDER';

//FOR CATEGORIES
export const ATTEMPTING_CATEGORIES = 'ATTEMPTING_CATEGORIES'
export const CATEGORIES_INIT = 'CATEGORIES_INIT'
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED'

//FOR PRODUCT
export const ATTEMPTING_POPULAR_PRODUCT = 'ATTEMPTING_POPULAR_PRODUCT'
export const POPULAR_PRODUCT_INIT = 'POPULAR_PRODUCT_INIT'
export const POPULAR_PRODUCT_FAILED = 'POPULAR_PRODUCT_FAILED'

//FOR GIFT
export const ATTEMPTING_GIFT_FOR = 'ATTEMPTING_GIFT_FOR'
export const GIFT_FOR_INIT = 'GIFT_FOR_INIT'
export const GIFT_FOR_FAILED = 'GIFT_FOR_FAILED'

//FOR GIFT SEARCH
export const ATTEMPTING_GIFT_PRODUCT_SEARCH = 'ATTEMPTING_GIFT_PRODUCT_SEARCH'
export const GIFT_PRODUCT_SEARCH = 'GIFT_PRODUCT_SEARCH'
export const GIFT_PRODUCT_SEARCH_FILTER = 'GIFT_PRODUCT_SEARCH_FILTER'
export const GIFT_PRODUCT_SEARCH_FAILED = 'GIFT_PRODUCT_SEARCH_FAILED'

//FOR EVENT
export const ATTEMPTING_POPULAR_EVENT = 'ATTEMPTING_POPULAR_EVENT'
export const POPULAR_EVENT_HOME_INIT = 'POPULAR_EVENT_HOME_INIT'
export const POPULAR_EVENT_HOME_FAILED = 'POPULAR_EVENT_HOME_FAILED'
export const ATTEMPTING_EVENTS_HOME = 'ATTEMPTING_EVENTS_HOME'
export const GET_EVENTS_HOME_FAILED = 'GET_EVENTS_HOME_FAILED'
export const GET_ALL_HOME_EVENTS = 'GET_ALL_HOME_EVENTS'
