# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  # use_frameworks! :linkage => linkage.to_sym
  use_frameworks! :linkage => :static
end

install! 'cocoapods', :deterministic_uuids => false
use_frameworks! :linkage => :static

target 'Regards' do
  config = use_native_modules!

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseMessagingInterop', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'GoogleTagManager', :modular_headers => true

  $RNFirebaseAsStaticFramework = true
  $RNFirebaseAnalyticsWithoutAdIdSupport=true
  # $RNFirebaseAnalyticsEnableAdSupport = true
  
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    # pod 'RNGosellSdkReactNative', :path => '../node_modules/@tap-payments/gosell-sdk-react-native'
    pod 'RNLocalize', :path => '../node_modules/react-native-localize'
    pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'
    pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' if config.name == 'Debug'
      end
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

target 'ImageNotification' do
  use_frameworks! :linkage => :static
  pod 'FirebaseCoreInternal'
  pod 'GoogleUtilities'
  pod 'Firebase/Messaging'
  
end