export const ATTEMPTING_LOGIN_CORPORATE  = "ATTEMPTING_LOGIN_CORPORATE";
export const SUCCESS_LOGIN_CORPORATE  = "SUCCESS_LOGIN_CORPORATE";
export const FAILED_LOGIN_CORPORATE  = "FAILED_LOGIN_CORPORATE";
export const CLEANUP_LOGIN_CORPORATE = "CLEANUP_LOGIN_CORPORATE";