//FOR IMAGE PROFILE
export const IMAGE_PROFILE_SUCCESS  = 'IMAGE_PROFILE_SUCCESS';
export const IMAGE_PROFILE_FAILED   = 'IMAGE_PROFILE_FAILED';
export const ATTEMPTING_IMAGE_PROFILE = 'ATTEMPTING_IMAGE_PROFILE';

//FOR PROFILE
export const GET_PROFILE  = 'GET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPDATE_PROFILE  = 'UPDATE_PROFILE';
export const DELETE_PROFILE  = 'DELETE_PROFILE';
export const GET_PROFILE_FAILED   = 'GET_PROFILE_FAILED';
export const ATTEMPTING_GET_PROFILE = 'ATTEMPTING_GET_PROFILE';

//FOR IMAGE PROFILE
export const GET_ORDERS  = 'GET_ORDERS';
export const ORDERS_FAILED   = 'ORDERS_FAILED';
export const ATTEMPTING_ORDERS  = 'ATTEMPTING_ORDERS';

//FOR DELETE ACCOUNT 
export const DELETE_ACCOUNT  = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_CLEAN  = 'DELETE_ACCOUNT_CLEAN';
export const DELETE_ACCOUNT_FAILED   = 'DELETE_ACCOUNT_FAILED';
export const ATTEMPTING_DELETE_ACCOUNT = 'ATTEMPTING_DELETE_ACCOUNT';


//FOR GIFTS
export const ATTEMPTING_MyGIFT  = 'ATTEMPTING_MyGIFT';
export const MyGIFT_ORDERS  = 'MyGIFT_ORDERS';
export const MyGIFT_FAILED  = 'MyGIFT_FAILED';