export Title from "./Title";
export Logo from './Logo';
export LogoSplash from './LogoSplash';
export Card from './Card';
export Head from './Head';
export ImageCricle from './ImageCricle'
export HeaderHome from './Home/HeaderHome';
export Header from './Home/Header'
export CardService from './Home/CardService'
export CategoryEgde from './Category/CategoryEgde';
export CategoryItem from './Category/CategoryItem';
export Carousel from './Carousel';
export CarouselSimple from './Carousel/v2';
export PopularProduct from './Product/PopularProduct';
export PopularItem from './PopularItem';
export Button from './Button';
export Gifts from './Gifts';
export Hr from './Hr';
export TextInput from './TextInput';
export Input from './Input'
export InputSearch from './Search/InputSearch';
export Search from "./Home/Search";
export SliderImage from './Product/ProductDetails/SliderImage';
export DetailsCard from './Product/ProductDetails/DetailsCard';
export ProductButton from './Product/ProductDetails/DetailsCard/ProductButton'
export Quantity from './Product/ProductDetails/DetailsCard/Quantity'
export QuantityInput from './Product/ProductDetails/QuantityInput'
export InputPhone from './Product/ProductDetails/InputPhone'
export CardPhone from './Product/ProductDetails/CardPhone'
export ButtonGroup from './ButtonGroup'
export CardImage from './Payment/CardImage'
export CreditCard from './Payment/CreditCard'
export SelectPayment from './Payment/SelectPayment'
export ButtonApple from './Payment/ButtonApple'
export ButtonApp from './ButtonApp'
export ImageProfile from './Profile/ImageProfile'
export ItemProfile from './Profile/ItemProfile'
export ItemHistory from './History/ItemHistory'
export CustomModel from './CustomModel'
export InputEmail from './InputEmail'
export InputPassword from './InputPassword'
export ItemMyGift from './MyGift/ItemMyGift'
export AutoScrollFlatList from './AutoScrollFlatList'
export UniversalImage from './UniversalImage'