//FOR OTP
export const ATTEMPTING_OTP  = 'ATTEMPTING_OTP';
export const SEND_OTP_SUCCESS  = 'SEND_OTP_SUCCESS';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const CHECK_OTP_SUCCESS  = 'CHECK_OTP_SUCCESS';
export const OTP_FAILED   = 'OTP_FAILED';

//FOR LOGOUT
export const LOGOUT = 'LOGOUT';

//FOR ADD FAVOURITE
export const ATTEMPTING_ADD_FAVOURITE  = 'ATTEMPTING_ADD_FAVOURITE';
export const ADD_FAVOURITE_SUCCESS  = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAILED  = 'ADD_FAVOURITE_FAILED';

//FOR ADD WALLET
export const ATTEMPTING_MYWALLET = 'ATTEMPTING_MYWALLET';
export const MYWALLET_FAILED = 'MYWALLET_FAILED';
export const GET_MYWALLET = 'GET_MYWALLET';
export const CLEAR_MYWALLET = 'CLEAR_MYWALLET';

//FOR LOCATION
export const ATTEMPTING_LOCATION = 'ATTEMPTING_LOCATION';
export const GET_LOCATION = 'GET_LOCATION';
