export const ATTEMPTING_PAYMENTS  = "ATTEMPTING_PAYMENTS";
export const PAYMENTS_SUCCESS  = "PAYMENTS_SUCCESS";
export const PAYMENTS_ORDER  = "PAYMENTS_ORDER";
export const PAYMENTS_FAILED  = "PAYMENTS_FAILED";
export const PAYMENTS_CLEANUP  = "PAYMENTS_CLEANUP";
export const PAYMENTS_CANCLED = "PAYMENTS_CANCLED";


//Promo
export const ATTEMPTING_PROMO  = "ATTEMPTING_PROMO";
export const PROMO_SUCCESS  = "PROMO_SUCCESS";
export const PROMO_FAILED  = "PROMO_FAILED";
export const PROMO_RELOAD  = "PROMO_RELOAD";

//WALLET
export const ATTEMPTING_OTP_PAYWALLET  = "ATTEMPTING_OTP_PAYWALLET";
export const OTP_PAYWALLET_SUCCESS  = "OTP_PAYWALLET_SUCCESS";
export const OTP_PAYWALLET_FAILED  = "OTP_PAYWALLET_FAILED";
export const OTP_PAYWALLET_CLEANUP = "OTP_PAYWALLET_CLEANUP";    

export const ATTEMPTING_PAYWALLET  = "ATTEMPTING_PAYWALLET";
export const PAYWALLET_SUCCESS  = "PAYWALLET_SUCCESS";
export const PAYWALLET_ORDER  = "PAYWALLET_ORDER";
export const PAYWALLET_FAILED  = "PAYWALLET_FAILED";
export const PAYWALLET_CLEANUP  = "PAYWALLET_CLEANUP";
export const PAYWALLET_CANCLED  = "PAYWALLET_CANCLED";