//FOR SEARCH
export const ATTEMPTING_SEARCH = 'ATTEMPTING_SEARCH'
export const GET_SEARCH = 'GET_SEARCH'
// export const GET_ALL_SELLER = 'GET_ALL_SELLER'
export const GET_SEARCH_FAILED = 'GET_SEARCH_FAILED'

//FOR GATEGORIES
export const ATTEMPTING_GATEGORIES = 'ATTEMPTING_GATEGORIES'
export const GET_POPULAR_GATEGORIES = 'GET_POPULAR_GATEGORIES'
export const GET_ALL_GATEGORIES = 'GET_ALL_GATEGORIES'
export const ALL_GATEGORIES = 'ALL_GATEGORIES'
export const GET_GATEGORIES_FAILED = 'GET_GATEGORIES_FAILED'

//FOR EVENTS
export const ATTEMPTING_EVENTS = 'ATTEMPTING_EVENTS'
export const GET_POPULAR_EVENTS = 'GET_POPULAR_EVENTS'
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS'
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED'

//FOR SELLER
export const ATTEMPTING_SELLER = 'ATTEMPTING_SELLER'
export const GET_POPULAR_SELLER = 'GET_POPULAR_SELLER'
export const GET_ALL_SELLER = 'GET_ALL_SELLER'
export const GET_SELLER_BY_HOME = 'GET_SELLER_BY_HOME'
export const GET_SELLER_FAILED = 'GET_SELLER_FAILED'

//FOR  PRODUCT BY SELLER
export const ATTEMPTING_PRODUCT_BY_SELLER = 'ATTEMPTING_PRODUCT_BY_SELLER'
export const GET_PRODUCT_BY_SELLER = 'GET_PRODUCT_BY_SELLER'
export const PRODUCT_BY_SELLER_FAILED = 'PRODUCT_BY_SELLER_FAILED'

//FOR  PRODUCT BY EVENTS
export const ATTEMPTING_PRODUCT_BY_EVENTS = 'ATTEMPTING_PRODUCT_BY_EVENTS'
export const GET_PRODUCT_BY_EVENTS = 'GET_PRODUCT_BY_EVENTS'
export const PRODUCT_BY_EVENTS_FAILED = 'PRODUCT_BY_EVENTS_FAILED'

//FOR  PRODUCT BY CATEGORIES
export const ATTEMPTING_PRODUCT_BY_CATEGORIES = 'ATTEMPTING_PRODUCT_BY_CATEGORIES'
export const GET_PRODUCT_BY_CATEGORIES = 'GET_PRODUCT_BY_CATEGORIES'
export const PRODUCT_BY_CATEGORIES_FAILED = 'PRODUCT_BY_CATEGORIES_FAILED'